import React, { useEffect, useMemo, useState } from "react";
import { Image, Modal, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { LinearGradient } from "expo-linear-gradient";
import { SafeAreaView } from "react-native-safe-area-context";
import * as Clipboard from "expo-clipboard";
import { getCouponImageUrl, getCoupons } from "../../../services/couponService";
import AppHeader from "../../../components/AppHeader";

const CATEGORIES = [
  { key: "bus", label: "Bus", icon: "bus-outline" },
  { key: "flight", label: "Flights", icon: "airplane-outline" },
  { key: "hotel", label: "Hotels", icon: "bed-outline" },
];

const money = (value) => value === undefined || value === null || value === "" ? "" : `₹${Number(value).toLocaleString("en-IN")}`;
const formatDate = (value) => { const date = new Date(value); return Number.isNaN(date.getTime()) ? "" : date.toLocaleDateString("en-IN", { day: "2-digit", month: "short" }); };
const daysUntil = (value) => { const time = new Date(value).getTime(); return Number.isNaN(time) ? null : Math.ceil((time - Date.now()) / 86400000); };
const discountText = (offer) => offer.value === undefined || offer.value === null || offer.value === "" ? "SPECIAL OFFER" : String(offer.couponType || "").toLowerCase().includes("percent") ? `${offer.value}% OFF` : `${money(offer.value)} OFF`;
const badgesFor = (offer) => offer.isExclusive ? ["EXCLUSIVE"] : offer.isFirstTimeUserOnly ? ["FIRST BOOKING"] : offer.isAutoApply ? ["AUTO APPLY"] : [];
const conditionText = (offer) => offer.isFirstTimeUserOnly ? "First booking offer" : offer.isAutoApply ? "Applied automatically at checkout" : offer.isExclusive ? "Exclusive PickNBook offer" : offer.promotionCategory || "Selected travel bookings";
const expiryText = (offer) => { const days = daysUntil(offer.expiryDate); return days !== null && days >= 0 && days <= 30 ? `Ends in ${days} day${days === 1 ? "" : "s"}` : offer.expiryDate ? `Ends ${formatDate(offer.expiryDate)}` : "Limited time"; };

function OfferImage({ offer, index, style }) {
  const service = String(offer.serviceType || "").toLowerCase();
  const icon = service === "flight" ? "airplane" : service === "hotel" ? "bed" : "bus";
  if (offer.imageUrl) return <Image source={{ uri: getCouponImageUrl(offer.imageUrl) }} style={style} resizeMode="cover" />;
  return <LinearGradient colors={index % 2 ? ["#17233D", "#385784"] : ["#A9112B", "#EF3340"]} style={[style, styles.imageFallback]}><Ionicons name={icon} size={48} color="rgba(255,255,255,0.34)" /><Text style={styles.fallbackText}>TRAVEL MORE. SAVE MORE.</Text></LinearGradient>;
}

function SkeletonCard() {
  return <View style={styles.skeletonCard}><View style={[styles.skeleton, styles.skeletonImage]} /><View style={styles.skeletonBody}><View style={[styles.skeleton, styles.skeletonPill]} /><View style={[styles.skeleton, styles.skeletonTitle]} /><View style={[styles.skeleton, styles.skeletonLine]} /><View style={[styles.skeleton, styles.skeletonCode]} /></View></View>;
}

function OfferCard({ offer, index, onPress, onCopy, copiedCode }) {
  const code = offer.couponCode || "PICKNBOOK";
  return <Pressable style={styles.offerCard} onPress={() => onPress(offer)}>
    <View><OfferImage offer={offer} index={index} style={styles.offerImage} /></View>
    <View style={styles.offerBody}><View style={styles.offerHeadingRow}><Text style={styles.offerTitle} numberOfLines={2}>{offer.title || offer.promotionCategory || "Travel offer"}</Text><Text style={styles.expiryText}>{expiryText(offer)}</Text></View><Text style={styles.condition} numberOfLines={1}>{conditionText(offer)}</Text><View style={styles.metaRow}><Text style={styles.metaLabel}>Min. booking</Text><Text style={styles.metaValue}>{money(offer.minBookingAmount) || "No minimum"}</Text><Text style={styles.metaLabel}>Max discount</Text><Text style={styles.metaValue}>{money(offer.maxDiscountAmount) || "—"}</Text></View><View style={styles.couponStrip}><View style={styles.couponCopy}><Text style={styles.couponLabel}>COUPON CODE</Text><Text style={styles.couponCode}>{code}</Text></View><Pressable style={styles.copyButton} onPress={(event) => { event.stopPropagation?.(); onCopy(code); }}><Ionicons name={copiedCode === code ? "checkmark" : "copy-outline"} size={14} color="#FFFFFF" /><Text style={styles.copyText}>{copiedCode === code ? "COPIED" : "COPY"}</Text></Pressable></View></View>
  </Pressable>;
}

export default function OffersScreen() {
  const [category, setCategory] = useState("bus");
  const [offers, setOffers] = useState([]);
  const [loading, setLoading] = useState(true);
  const [selectedOffer, setSelectedOffer] = useState(null);
  const [copiedCode, setCopiedCode] = useState("");

  useEffect(() => { let mounted = true; setLoading(true); getCoupons(category).then((items) => mounted && setOffers(items)).catch(() => mounted && setOffers([])).finally(() => mounted && setLoading(false)); return () => { mounted = false; }; }, [category]);
  const selectedCategory = useMemo(() => CATEGORIES.find((item) => item.key === category), [category]);
  const handleCopy = async (code) => { await Clipboard.setStringAsync(code); setCopiedCode(code); setTimeout(() => setCopiedCode((current) => current === code ? "" : current), 1600); };

  return <SafeAreaView style={styles.screen} edges={["left", "right", "bottom"]}><AppHeader title="Offers" /><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.scrollContent}>
    <LinearGradient colors={["#FFF0F3", "#FFF9FA", "#F8FAFC"]} style={styles.hero}><View style={styles.heroTopRow}><View style={styles.heroCopy}><Text style={styles.eyebrow}>PICKNBOOK REWARDS</Text><Text style={styles.heroTitle}>Travel more.</Text><Text style={styles.heroAccent}>Save more.</Text></View><View style={styles.heroIcon}><Ionicons name="gift-outline" size={27} color="#D11F35" /></View></View><Text style={styles.heroSubtitle}>Unlock exclusive savings across buses, flights and hotels.</Text><View style={styles.trustRow}><Ionicons name="shield-checkmark" size={16} color="#B4182A" /><Text style={styles.trustText}>Verified offers · Updated regularly</Text></View></LinearGradient>
    <View style={styles.categorySection}><Text style={styles.sectionKicker}>EXPLORE SAVINGS</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.categoryRow}>{CATEGORIES.map((item) => { const active = category === item.key; return <Pressable key={item.key} onPress={() => setCategory(item.key)} style={[styles.category, active && styles.categoryActive]}><Ionicons name={item.icon} size={18} color={active ? "#FFFFFF" : "#64748B"} /><Text style={[styles.categoryText, active && styles.categoryTextActive]}>{item.label}</Text></Pressable>; })}</ScrollView></View>
    <View style={styles.content}><View style={styles.sectionHeader}><View><Text style={styles.sectionTitle}>{selectedCategory?.label} offers</Text><Text style={styles.sectionSubtitle}>Save on your next journey</Text></View>{!loading && offers.length > 0 ? <View style={styles.countPill}><Text style={styles.countText}>{offers.length} LIVE</Text></View> : null}</View>{loading ? <><SkeletonCard /><SkeletonCard /></> : offers.length ? offers.map((offer, index) => <OfferCard key={String(offer.id || offer.couponCode || index)} offer={offer} index={index} onPress={setSelectedOffer} onCopy={handleCopy} copiedCode={copiedCode} />) : <View style={styles.empty}><View style={styles.emptyIcon}><Ionicons name="sparkles-outline" size={28} color="#E52332" /></View><Text style={styles.emptyTitle}>No offers available</Text><Text style={styles.emptyText}>Check back soon for new savings.</Text></View>}</View>
  </ScrollView>
  <Modal visible={!!selectedOffer} transparent animationType="slide" onRequestClose={() => setSelectedOffer(null)}><View style={styles.modalOverlay}><View style={styles.sheet}>{selectedOffer ? <><View style={styles.sheetHandle} /><OfferImage offer={selectedOffer} index={0} style={styles.sheetImage} /><View style={styles.sheetBody}><View style={styles.sheetTitleRow}><Text style={styles.sheetTitle}>{selectedOffer.title || selectedOffer.promotionCategory || "Travel offer"}</Text><Pressable onPress={() => setSelectedOffer(null)}><Ionicons name="close-circle" size={25} color="#94A3B8" /></Pressable></View><Text style={styles.sheetDiscount}>{discountText(selectedOffer)}</Text><Text style={styles.sheetCondition}>{conditionText(selectedOffer)}</Text><View style={styles.conditions}><Text style={styles.conditionsTitle}>Offer conditions</Text><Text style={styles.conditionItem}>• Minimum booking: {money(selectedOffer.minBookingAmount) || "No minimum"}</Text><Text style={styles.conditionItem}>• Maximum discount: {money(selectedOffer.maxDiscountAmount) || "As applicable"}</Text><Text style={styles.conditionItem}>• {expiryText(selectedOffer)}</Text></View><View style={styles.sheetCoupon}><View><Text style={styles.couponLabel}>COUPON CODE</Text><Text style={styles.couponCode}>{selectedOffer.couponCode || "PICKNBOOK"}</Text></View><Pressable style={styles.copyButton} onPress={() => handleCopy(selectedOffer.couponCode || "PICKNBOOK")}><Text style={styles.copyText}>{copiedCode === (selectedOffer.couponCode || "PICKNBOOK") ? "COPIED" : "COPY"}</Text></Pressable></View></View></> : null}</View></View></Modal>
  </SafeAreaView>;
}

const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: "#F8FAFC" }, scrollContent: { paddingBottom: 32 },
  hero: { margin: 16, marginBottom: 0, padding: 20, borderRadius: 24, overflow: "hidden" }, heroTopRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start" }, heroCopy: { flex: 1 }, eyebrow: { color: "#A52D3D", fontSize: 10, fontWeight: "800", letterSpacing: 1.4, marginBottom: 8 }, heroTitle: { color: "#111827", fontSize: 27, lineHeight: 31, fontWeight: "800", letterSpacing: -0.8 }, heroAccent: { color: "#D1263A", fontSize: 27, lineHeight: 31, fontWeight: "800", letterSpacing: -0.8 }, heroSubtitle: { color: "#64748B", fontSize: 13, lineHeight: 19, marginTop: 12, maxWidth: 300 }, heroIcon: { width: 54, height: 54, borderRadius: 19, backgroundColor: "#FFFFFF", alignItems: "center", justifyContent: "center", shadowColor: "#D1263A", shadowOpacity: 0.12, shadowRadius: 12, shadowOffset: { width: 0, height: 5 }, elevation: 3 }, trustRow: { flexDirection: "row", alignItems: "center", marginTop: 15, gap: 6 }, trustText: { color: "#8E3442", fontSize: 12, fontWeight: "600" },
  categorySection: { paddingTop: 20, paddingBottom: 2 }, sectionKicker: { paddingHorizontal: 20, color: "#94A3B8", fontSize: 10, fontWeight: "800", letterSpacing: 1.2, marginBottom: 10 }, categoryRow: { paddingHorizontal: 20, gap: 9 }, category: { minWidth: 96, height: 42, paddingHorizontal: 13, borderRadius: 14, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 7, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#E8EDF4" }, categoryActive: { backgroundColor: "#E52332", borderColor: "#E52332", shadowColor: "#E52332", shadowOpacity: 0.2, shadowRadius: 8, shadowOffset: { width: 0, height: 4 }, elevation: 3 }, categoryText: { color: "#64748B", fontSize: 13, fontWeight: "700" }, categoryTextActive: { color: "#FFFFFF" },
  content: { paddingHorizontal: 16, paddingTop: 23 }, sectionHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 14 }, sectionTitle: { color: "#111827", fontSize: 20, fontWeight: "800" }, sectionSubtitle: { color: "#94A3B8", fontSize: 12, marginTop: 3 }, countPill: { paddingHorizontal: 9, paddingVertical: 6, borderRadius: 9, backgroundColor: "#EAF8F2" }, countText: { color: "#16845A", fontSize: 10, fontWeight: "800", letterSpacing: 0.4 },
  offerCard: { backgroundColor: "#FFFFFF", borderRadius: 20, overflow: "hidden", marginBottom: 16, shadowColor: "#0F172A", shadowOpacity: 0.07, shadowRadius: 15, shadowOffset: { width: 0, height: 5 }, elevation: 3 }, offerImage: { width: "100%", height: 178, backgroundColor: "#E2E8F0" }, imageFallback: { alignItems: "center", justifyContent: "center", gap: 7 }, fallbackText: { color: "rgba(255,255,255,0.72)", fontSize: 10, fontWeight: "800", letterSpacing: 1.3 }, imageShade: { position: "absolute", left: 0, right: 0, bottom: 0, height: 48, backgroundColor: "rgba(0,0,0,0.08)" }, imageBadgeRow: { position: "absolute", left: 14, right: 14, bottom: 12, flexDirection: "row", alignItems: "center", gap: 7 }, discountBadge: { paddingHorizontal: 10, paddingVertical: 6, borderRadius: 8, backgroundColor: "#FFF0F2" }, discountText: { color: "#C21832", fontSize: 12, fontWeight: "900" }, statusBadge: { paddingHorizontal: 9, paddingVertical: 6, borderRadius: 8, backgroundColor: "rgba(255,255,255,0.9)" }, statusText: { color: "#475569", fontSize: 9, fontWeight: "900", letterSpacing: 0.4 }, offerBody: { padding: 15 }, offerHeadingRow: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: 9 }, offerTitle: { flex: 1, color: "#111827", fontSize: 18, lineHeight: 23, fontWeight: "800" }, expiryText: { color: "#94A3B8", fontSize: 11, fontWeight: "700", paddingTop: 3 }, condition: { color: "#64748B", fontSize: 13, marginTop: 5 }, metaRow: { flexDirection: "row", alignItems: "center", flexWrap: "wrap", gap: 5, marginTop: 12 }, metaLabel: { color: "#94A3B8", fontSize: 11 }, metaValue: { color: "#334155", fontSize: 11, fontWeight: "700", marginRight: 7 }, couponStrip: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginTop: 14, padding: 10, borderRadius: 12, borderWidth: 1, borderColor: "#F1D7DA", borderStyle: "dashed", backgroundColor: "#FFFAFA" }, couponCopy: { flex: 1 }, couponLabel: { color: "#9CA3AF", fontSize: 9, fontWeight: "800", letterSpacing: 1 }, couponCode: { color: "#1F2937", fontSize: 15, fontWeight: "900", letterSpacing: 1, marginTop: 2 }, copyButton: { flexDirection: "row", alignItems: "center", gap: 4, paddingHorizontal: 11, paddingVertical: 8, borderRadius: 8, backgroundColor: "#E52332" }, copyText: { color: "#FFFFFF", fontSize: 10, fontWeight: "900" },
  skeletonCard: { backgroundColor: "#FFFFFF", borderRadius: 20, overflow: "hidden", marginBottom: 16 }, skeleton: { backgroundColor: "#E8EDF4" }, skeletonImage: { height: 178 }, skeletonBody: { padding: 15 }, skeletonPill: { width: 86, height: 23, borderRadius: 7 }, skeletonTitle: { width: "75%", height: 21, borderRadius: 6, marginTop: 12 }, skeletonLine: { width: "48%", height: 14, borderRadius: 6, marginTop: 9 }, skeletonCode: { height: 44, borderRadius: 12, marginTop: 14 }, empty: { alignItems: "center", paddingTop: 45 }, emptyIcon: { width: 66, height: 66, borderRadius: 22, alignItems: "center", justifyContent: "center", backgroundColor: "#FFE8EB" }, emptyTitle: { color: "#111827", fontSize: 17, fontWeight: "800", marginTop: 16 }, emptyText: { color: "#64748B", fontSize: 13, marginTop: 6 },
  modalOverlay: { flex: 1, justifyContent: "flex-end", backgroundColor: "rgba(15,23,42,0.35)" }, sheet: { backgroundColor: "#FFFFFF", borderTopLeftRadius: 26, borderTopRightRadius: 26, overflow: "hidden", maxHeight: "88%" }, sheetHandle: { width: 42, height: 4, borderRadius: 2, backgroundColor: "#CBD5E1", alignSelf: "center", marginVertical: 9 }, sheetImage: { width: "100%", height: 150 }, sheetBody: { padding: 18, paddingBottom: 28 }, sheetTitleRow: { flexDirection: "row", alignItems: "flex-start", gap: 10 }, sheetTitle: { flex: 1, color: "#111827", fontSize: 20, lineHeight: 25, fontWeight: "800" }, sheetDiscount: { color: "#C21832", fontSize: 15, fontWeight: "900", marginTop: 10 }, sheetCondition: { color: "#64748B", fontSize: 13, marginTop: 5 }, conditions: { marginTop: 18, paddingTop: 15, borderTopWidth: 1, borderTopColor: "#F1F5F9" }, conditionsTitle: { color: "#111827", fontSize: 14, fontWeight: "800", marginBottom: 8 }, conditionItem: { color: "#64748B", fontSize: 13, lineHeight: 21 }, sheetCoupon: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginTop: 17, padding: 11, borderRadius: 12, borderWidth: 1, borderColor: "#F1D7DA", borderStyle: "dashed", backgroundColor: "#FFFAFA" },
});
