import { StyleSheet, Platform } from "react-native";
import { COLORS, CARD_GAP } from "./HomeScreen";

/* ═══════════════ STYLES ═══════════════ */
export const styles = StyleSheet.create({
    root: {
        flex: 1,
        backgroundColor: "#F4F7FC",
    },
    safeArea: {
        flex: 1,
        backgroundColor: "#F4F7FC",
    },
    scrollView: {
        flex: 1,
    },
    scrollContent: {
        flexGrow: 1,
        paddingBottom: 40,
        backgroundColor: "#FFFFFF",
    },

    /* ── Hero Background & Header ── */
    heroBgContainer: {
        width: "100%",
        justifyContent: "space-between",
        paddingTop: Platform.OS === "android" ? 6 : 0,
    },
    heroBgImage: {
        opacity: 0.95,
    },
    headerBar: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingLeft: 10,
        paddingRight: 16,
        paddingVertical: 8,
    },
    headerLeft: {
        justifyContent: "center",
        alignItems: "flex-start",
    },
    headerAppIcon: {
        width: 45,
        height: 45,
        borderRadius: 14,
        borderWidth: 2,
        borderColor: "#000000",
    },
    headerRight: {
        flexDirection: "row",
        alignItems: "center",
        gap: 12,
    },
    notifBtn: {
        width: 42,
        height: 42,
        borderRadius: 21,
        backgroundColor: "#FFFFFF",
        alignItems: "center",
        justifyContent: "center",
        position: "relative",
        shadowColor: "#0F172A",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.08,
        shadowRadius: 10,
        elevation: 3,
    },
    notifBadge: {
        position: "absolute",
        top: 4,
        right: 4,
        width: 18,
        height: 18,
        borderRadius: 9,
        backgroundColor: COLORS.primary,
        alignItems: "center",
        justifyContent: "center",
        borderWidth: 2,
        borderColor: "#FFFFFF",
    },
    notifBadgeText: {
        color: "#FFFFFF",
        fontSize: 9,
        fontWeight: "900",
    },
    avatarWrap: {
        width: 42,
        height: 42,
        borderRadius: 21,
        backgroundColor: "#334155",
        alignItems: "center",
        justifyContent: "center",
        borderWidth: 2,
        borderColor: "#FFFFFF",
        shadowColor: "#0F172A",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.08,
        shadowRadius: 10,
        elevation: 3,
    },
    profileImage: {
        width: 38,
        height: 38,
        borderRadius: 19,
    },

    /* ── Hero Content Row ── */
    heroContentRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "flex-start",
        paddingHorizontal: 20,
        paddingTop: 12,
    },
    heroLeft: {
        flex: 1,
    },
    greetingRow: {
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 6,
        gap: 6,
    },
    greeting: {
        fontSize: 16,
        fontWeight: "900",
        color: "#0F172A",
    },
    headline: {
        fontSize: 34,
        fontWeight: "900",
        color: "#0F172A",
        lineHeight: 40,
        letterSpacing: -0.8,
    },
    headlineAccent: {
        color: COLORS.primary,
        fontStyle: "italic",
    },
    heroSubText: {
        fontSize: 14,
        fontWeight: "900",
        color: "#334155",
        textShadowColor: "rgba(51, 65, 85, 0.3)",
        textShadowOffset: { width: 0.5, height: 0.5 },
        textShadowRadius: 1,
        marginTop: 12,
        lineHeight: 20,
    },

    /* ── Weather Pill ── */
    weatherPill: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "rgba(255, 255, 255, 0.92)",
        borderRadius: 20,
        paddingHorizontal: 14,
        paddingVertical: 8,
        gap: 8,
        shadowColor: "#0F172A",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.06,
        shadowRadius: 10,
        elevation: 3,
    },
    weatherInfo: {
        flexDirection: "column",
    },
    weatherTemp: {
        fontSize: 16,
        fontWeight: "900",
        color: "#0F172A",
        lineHeight: 18,
    },
    weatherCity: {
        fontSize: 10,
        fontWeight: "600",
        color: "#64748B",
    },

    /* ── White Sheet Container ── */
    whiteSheet: {
        flex: 1,
        backgroundColor: "#FFFFFF",
        borderTopLeftRadius: 32,
        borderTopRightRadius: 32,
        marginTop: -20,
        paddingTop: 24,
        paddingBottom: 36,
        minHeight: 500,
    },

    /* ── 2x2 Grid Category Cards ── */
    gridContainer: {
        flexDirection: "row",
        flexWrap: "wrap",
        justifyContent: "space-between",
        paddingHorizontal: 24,
        gap: CARD_GAP,
    },
    gridCard: {
        height: 126,
        borderRadius: 20,
        paddingVertical: 8,
        paddingHorizontal: 9,
        borderWidth: 1,
        shadowColor: "#0F172A",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.04,
        shadowRadius: 10,
        elevation: 3,
        justifyContent: "space-between",
    },
    cardImageContainer: {
        width: '100%',
        height: 80,
        backgroundColor: 'transparent',
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 2,
    },
    busImageWrapper: {
        width: '100%',
        height: '100%',
        overflow: 'hidden',
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 14,
    },
    busImageScaled: {
        width: '185%',
        height: '185%',
    },
    cardBgImage: {
        width: '100%',
        height: '100%',
        backgroundColor: 'transparent',
    },
    cardContentBottom: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        minHeight: 26,
        gap: 6,
    },
    categoryTitle: {
        flex: 1,
        flexShrink: 1,
        fontSize: 16,
        fontWeight: "800",
        color: "#0F172A",
    },
    categoryArrow: {
        flexShrink: 0,
        width: 26,
        height: 26,
        borderRadius: 13,
        alignItems: "center",
        justifyContent: "center",
    },

    /* ── Section Shared ── */
    sectionWrap: {
        paddingHorizontal: 20,
        marginTop: 24,
        paddingBottom: 16,
    },
    sectionHeader: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        marginBottom: 14,
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: "800",
        color: "#0F172A",
        letterSpacing: -0.2,
    },
    viewAll: {
        fontSize: 13,
        fontWeight: "700",
        color: COLORS.primary,
    },

    /* ── Promo Banner ── */
    promoBanner: {
        borderRadius: 24,
        paddingVertical: 20,
        paddingLeft: 20,
        paddingRight: 12,
        flexDirection: "row",
        alignItems: "center",
        position: "relative",
        overflow: "hidden",
        shadowColor: COLORS.primary,
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.22,
        shadowRadius: 16,
        elevation: 6,
    },
    promoLeft: {
        flex: 1,
        paddingRight: 10,
        zIndex: 2,
    },
    promoBadgeText: {
        color: "rgba(255,255,255,0.85)",
        fontSize: 10,
        fontWeight: "900",
        letterSpacing: 0.8,
        marginBottom: 6,
    },
    promoHeadline: {
        color: "#FFFFFF",
        fontSize: 24,
        fontWeight: "900",
        letterSpacing: -0.5,
    },
    promoSub: {
        color: "rgba(255,255,255,0.9)",
        fontSize: 14,
        fontWeight: "600",
        marginTop: 2,
    },
    promoBtn: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "#FFFFFF",
        paddingHorizontal: 14,
        paddingVertical: 8,
        borderRadius: 14,
        alignSelf: "flex-start",
        marginTop: 14,
        gap: 4,
    },
    promoBtnText: {
        color: COLORS.primary,
        fontSize: 13,
        fontWeight: "800",
    },
    promoRight: {
        width: 130,
        height: 100,
        borderRadius: 16,
        overflow: "hidden",
    },
    promoBusImg: {
        width: "100%",
        height: "100%",
        borderRadius: 16,
    },
    paginationRow: {
        position: "absolute",
        bottom: 8,
        alignSelf: "center",
        flexDirection: "row",
        gap: 6,
    },
    dot: {
        width: 6,
        height: 6,
        borderRadius: 3,
        backgroundColor: "rgba(255, 255, 255, 0.4)",
    },
    dotActive: {
        width: 14,
        backgroundColor: "#FFFFFF",
    },

    /* ── Continue Planning ── */
    planCard: {
        backgroundColor: COLORS.card,
        borderRadius: 20,
        paddingVertical: 16,
        paddingHorizontal: 16,
        flexDirection: "row",
        alignItems: "center",
        borderWidth: 1,
        borderColor: "#F1F5F9",
        shadowColor: "#0F172A",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.03,
        shadowRadius: 10,
        elevation: 2,
    },
    planIconWrap: {
        width: 44,
        height: 44,
        borderRadius: 14,
        backgroundColor: "#FFF0F2",
        alignItems: "center",
        justifyContent: "center",
        marginRight: 14,
    },
    planContent: {
        flex: 1,
    },
    planRoute: {
        fontSize: 15,
        fontWeight: "800",
        color: "#0F172A",
    },
    planArrowText: {
        color: COLORS.textMuted,
    },
    planMeta: {
        fontSize: 12,
        fontWeight: "500",
        color: "#64748B",
        marginTop: 3,
    },

    /* ── Destinations ── */
    destScroll: {
        gap: 12,
        paddingRight: 20,
        paddingVertical: 10,
    },
    destCard: {
        width: 135,
        height: 165,
        borderRadius: 20,
        overflow: "hidden",
        shadowColor: "#0F172A",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.08,
        shadowRadius: 12,
        elevation: 4,
    },
    destImage: {
        flex: 1,
    },
    destImageStyle: {
        borderRadius: 20,
    },
    destOverlay: {
        flex: 1,
        borderRadius: 20,
        padding: 12,
        justifyContent: "space-between",
    },
    destFavBtn: {
        width: 28,
        height: 28,
        borderRadius: 14,
        backgroundColor: "rgba(255,255,255,0.3)",
        alignItems: "center",
        justifyContent: "center",
        alignSelf: "flex-end",
    },
    destBottom: {},
    destName: {
        color: "#FFFFFF",
        fontSize: 16,
        fontWeight: "900",
    },
    destSub: {
        color: "rgba(255,255,255,0.85)",
        fontSize: 10,
        fontWeight: "600",
        marginTop: 1,
    },
});
